In [ ]:
#Importing different classifiers
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [ ]:
#Cross validation 
from sklearn.cross_validation import cross_val_score
knn = KNeighborsClassifier(n_neighbors=44)
scores = cross_val_score(knn, df, y, cv=10, scoring='accuracy').mean()
print(scores)

In [ ]:
#Scikit learn accepts data in numeric format. Now, we'll have to convert the character variable into numeric. 
#We'll use the labelencoder function.
#In label encoding, each unique value of a variable gets assigned a number, i.e., 
#let's say a variable color has four values ['red','green','blue','pink'].

#Label encoding this variable will return output as: red = 2 green = 0 blue = 1 pink = 3

#load sklearn and encode all object type variables
from sklearn import preprocessing

for x in train.columns:
    if train[x].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(train[x].values))
        train[x] = lbl.transform(list(train[x].values))


In [ ]:
#For plotting pair wise graph using seaborn
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

columns = df.columns
for column in columns:
    sns.pairplot(df, x_vars=[column], y_vars=['Cover_Type'], size=4, kind='reg')    //gs code sprint

In [ ]:
#For merging or concatenation
https://chrisalbon.com/python/pandas_join_merge_dataframe.html

In [ ]:
df.head()
df.shape
print(df['Age'].dtype)

In [ ]:
#For replacing in whole dataframe
#replaces all male with 1 and all female with 0
df.replace({'male':1, 'female':0}, inplace = True)

In [ ]:
#For getting all unique values in column Embarked
pd.unique(df['Embarked'].values)
#or
list(df['Embarked'].unique())

In [ ]:
#To get total of null values 
df.isnull().sum()
#To drop all nan in Embarked column
df.dropna(subset=['Embarked'], how='any', inplace = True)

In [ ]:
#To get dummies columns for nominal features
df = pd.get_dummies(df, columns=['Embarked'])

In [ ]:
#To fill na with mean 
#All na in Age is filled with mean of Age
df['Age'].fillna((df['Age'].mean()), inplace = True)

In [ ]:
#To fill na with forward fill
df.fillna(method='ffill', inplace=True)

In [ ]:
#For seeing all the categorical values
categories = df.select_dtypes(exclude = [np.number])
categories.describe()

In [ ]:
#To fill with majority elements
#first find majority element
df['Fare'].value_counts()
#See the majority element
#Now fill with majority let's say 21
df = df.fillna({'Fare':21})

In [ ]:
#To convert numpy arrays to Panda DataFrame
df=pd.DataFrame(df)

In [2]:
#Arrays in python
a = []
for i in range (1,11):
    a.append(i*2)
    
for i in a:
    print(i, end=' ')

2 4 6 8 10 12 14 16 18 20 

In [ ]:
#Predicting Score
clf.fit(train, y)
clf.score(train, y)

In [ ]:
#For saving output to csv file
pd.DataFrame({'connection_id':cid, 'target':prediction}).set_index('connection_id').to_csv('predict_network_attack.csv')

In [ ]:
import numpy as np
>>> X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
>>> Y = np.array([1, 1, 1, 2, 2, 2])
>>> from sklearn.naive_bayes import GaussianNB
>>> clf = GaussianNB()
>>> clf.fit(X, Y)

In [2]:
#numpy arrays
import numpy as np
a=np.zeros([4,5])
print(a)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [ ]:
#numpy sorting
import numpy as np
np.sort(train_data[0])

In [ ]:
#enumerate in python just assigns index to each element in the list